/**
 * Default keyword seed list for Telegram group auto-search.
 * These are Indonesian search terms for digital goods trading groups.
 */
export const DEFAULT_KEYWORDS: string[] = [
  // ── Akun Email ─────────────────────────────────
  'jual beli gmail',
  'jual gmail fresh',
  'jual gmail old',
  'jual akun gmail',
  'jual beli email',
  'jual email verified',
  'jual gmail a2f',
  'jual gmail 2fa',
  'jual outlook',
  'jual yahoo mail',
  'jual akun email',
  'gmail fresh murah',
  'gmail bulk',
  'jual gmail aged',

  // ── Akun Sosmed ────────────────────────────────
  'jual beli akun',
  'jual beli sosmed',
  'jual akun instagram',
  'jual akun ig',
  'jual akun tiktok',
  'jual akun twitter',
  'jual akun x',
  'jual akun facebook',
  'jual akun fb',
  'jual akun telegram',
  'jual akun snapchat',
  'jual akun pinterest',
  'jual akun linkedin',
  'jual akun reddit',
  'jual akun discord',
  'jual followers',
  'jual likes ig',
  'jual views tiktok',
  'jual subscriber',
  'jual akun verified',
  'jual centang biru',

  // ── Akun Game ──────────────────────────────────
  'jual beli game',
  'jual akun game',
  'jual akun ml',
  'jual akun mobile legends',
  'jual akun ff',
  'jual akun free fire',
  'jual akun pubg',
  'jual akun genshin',
  'jual akun genshin impact',
  'jual akun honkai',
  'jual akun valorant',
  'jual akun roblox',
  'jual akun steam',
  'jual akun epic games',
  'jual akun minecraft',
  'jual akun clash of clans',
  'jual akun coc',
  'jual akun clash royale',
  'jual akun cod',
  'jual akun apex',
  'jual diamond ml',
  'jual diamond ff',
  'jual uc pubg',
  'jual robux',
  'jual akun ps',
  'jual akun playstation',
  'jual akun xbox',
  'jual akun nintendo',
  'jual top up game',
  'top up game murah',
  'jual voucher game',
  'jual gift card game',
  'jual akun higgs domino',
  'jual chip domino',
  'jual akun stumble guys',
  'jual akun fortnite',
  'jual akun dota',
  'jual akun lol',
  'jual akun wuthering waves',
  'jual akun zenless zone zero',

  // ── Streaming & Premium ────────────────────────
  'jual akun netflix',
  'jual netflix murah',
  'jual akun spotify',
  'jual spotify premium',
  'jual akun youtube premium',
  'jual akun disney plus',
  'jual akun disney+',
  'jual akun hbo',
  'jual akun viu',
  'jual akun vidio',
  'jual akun wetv',
  'jual akun prime video',
  'jual akun amazon prime',
  'jual akun apple tv',
  'jual akun crunchyroll',
  'jual akun iqiyi',
  'jual akun canva',
  'jual canva pro',
  'jual akun chatgpt',
  'jual akun openai',
  'jual chatgpt plus',
  'jual akun midjourney',
  'jual akun grammarly',
  'jual akun zoom',
  'jual akun deezer',
  'jual akun tidal',
  'jual akun apple music',

  // ── Cloud & Hosting ────────────────────────────
  'jual akun aws',
  'jual aws free trial',
  'jual akun google cloud',
  'jual akun gcp',
  'jual akun azure',
  'jual akun digitalocean',
  'jual droplet',
  'jual vps murah',
  'jual rdp',
  'jual rdp murah',
  'jual akun heroku',
  'jual akun linode',
  'jual akun vultr',
  'jual domain murah',
  'jual hosting murah',
  'jual cpanel',
  'jual akun oracle cloud',

  // ── VPN & Proxy ────────────────────────────────
  'jual vpn',
  'jual vpn premium',
  'jual akun nordvpn',
  'jual akun expressvpn',
  'jual akun surfshark',
  'jual ssh premium',
  'jual vmess',
  'jual trojan vpn',
  'jual v2ray',
  'jual wireguard',
  'jual proxy',
  'jual socks5',

  // ── Software & License ─────────────────────────
  'jual license',
  'jual lisensi',
  'jual key windows',
  'jual windows original',
  'jual key office',
  'jual microsoft office',
  'jual adobe',
  'jual akun adobe',
  'jual photoshop',
  'jual akun figma',
  'jual antivirus',
  'jual key kaspersky',
  'jual key eset',
  'jual software murah',
  'jual apk mod',
  'jual apk premium',
  'jual iptv',

  // ── E-Wallet & Fintech ─────────────────────────
  'jual saldo',
  'jual saldo dana',
  'jual saldo gopay',
  'jual saldo ovo',
  'jual saldo shopeepay',
  'jual voucher',
  'jual voucher google play',
  'jual voucher playstore',
  'jual gift card',
  'jual itunes',
  'jual google play card',
  'jual steam wallet',
  'jual paypal balance',
  'jual saldo paypal',
  'jual akun paypal',

  // ── Education ──────────────────────────────────
  'jual akun ruangguru',
  'jual akun zenius',
  'jual akun coursera',
  'jual akun udemy',
  'jual akun skillshare',
  'jual akun scribd',
  'jual akun chegg',
  'jual akun duolingo',
  'jual akun linkedin learning',

  // ── Crypto & Trading ───────────────────────────
  'jual akun binance',
  'jual akun bybit',
  'jual akun trading',
  'jual signal trading',
  'jual bot trading',
  'jual usdt',
  'jual bitcoin',
  'jual crypto',
  'airdrop crypto',
  'jual akun coinbase',

  // ── Nomor & SIM ────────────────────────────────
  'jual nomor',
  'jual nomor hp',
  'jual sim card',
  'jual nomor cantik',
  'jual otp',
  'jual sms verify',
  'jual nomor virtual',
  'jual esim',

  // ── Marketplace & E-Commerce ───────────────────
  'jual akun shopee',
  'jual akun tokopedia',
  'jual akun lazada',
  'jual akun bukalapak',
  'jual akun blibli',
  'jual akun amazon',
  'jual akun ebay',
  'jual akun alibaba',

  // ── Transport & Food ───────────────────────────
  'jual akun grab',
  'jual akun gojek',
  'jual promo grab',
  'jual promo gojek',
  'jual voucher grabfood',
  'jual voucher gofood',
  'jual akun maxim',

  // ── Generic Digital Goods ──────────────────────
  'jual beli digital',
  'jual produk digital',
  'jual akun premium',
  'jual akun murah',
  'toko digital',
  'lapak digital',
  'digital store',
  'jual beli online',
  'marketplace digital',
  'jual beli receh',
  'share akun',
  'sharing akun',
  'free trial akun',
  'jual data',
  'jual database',
  'jual leads',
  'jual tools',
  'jual bot telegram',
  'jual script',
  'jual source code',
  'jasa pembuatan bot',
  'jual panel smm',
  'jual smm panel',
  'jual followers murah',

  // ── Catch-all Trading Groups ───────────────────
  'grup jual beli',
  'group jual beli',
  'jual beli bebas',
  'free share link',
  'share link gratis',
  'link grup telegram',
  'grup promosi',
  'grup iklan',
  'promosi gratis',
  'iklan gratis',
  'pasang iklan',
  'promo telegram',
  'jual beli indonesia',
  'marketplace indonesia',
  'lapak online',
  'olshop telegram',
];
