/**
 * Feature-scoped Bahasa Indonesia copy (DESIGN_SYSTEM.md §14).
 *
 * The shared UI chrome copy lives in `@/lib/strings`; this module holds the
 * page/feature-specific copy owned by the feature layer, so nothing is hardcoded
 * inline in components and future EN support stays cheap. Code identifiers stay
 * English (.claude/rules/naming-conventions.md §5).
 */
export const featureStrings = {
  overview: {
    subtitle: 'Ikhtisar operasi dan performa real-time.',
    ordersToday: 'Pesanan Hari Ini',
    successRate: 'Tingkat Keberhasilan',
    revenue: 'Pendapatan Hari Ini',
    activeExecutions: 'Eksekusi Aktif',
    healthyAccounts: 'Akun Sehat',
    queueDepth: 'Antrian',
    ordersOverTime: 'Pesanan dari Waktu ke Waktu',
    ordersSeriesLabel: 'Pesanan',
    statusDistribution: 'Distribusi Status Pesanan',
    recentOrders: 'Pesanan Terbaru',
    liveExecutions: 'Eksekusi Langsung',
    recentFailures: 'Kegagalan Terbaru',
  },

  suppliers: {
    subtitle: 'Kelola supplier bot dan pemetaan workflow default.',
    add: 'Tambah Supplier',
    edit: 'Ubah Supplier',
    name: 'Nama',
    botUsername: 'Username Bot',
    boundAccounts: 'Akun Terikat',
    defaultWorkflow: 'Workflow Default',
    successRate: 'Tingkat Keberhasilan',
    avgTime: 'Rata-rata Waktu',
    status: 'Status',
    lastError: 'Kesalahan Terakhir',
    testWorkflow: 'Uji Workflow Default',
    deleteConfirm: 'Hapus supplier ini? Produk yang terhubung akan kehilangan pemetaannya.',
    noWorkflow: 'Tanpa workflow',
    selectAccounts: 'Pilih akun',
  },

  accounts: {
    subtitle: 'Akun Telegram (MTProto) yang menjalankan pembelian ke supplier.',
    add: 'Tambah Akun',
    label: 'Label',
    phone: 'Nomor Telepon',
    phoneMasked: 'Telepon',
    status: 'Status',
    lastActivity: 'Aktivitas Terakhir',
    deleteConfirm: 'Hapus akun ini? Sesi login di server akan dicabut.',
    login: {
      title: 'Masuk Akun Telegram',
      stepPhone: 'Nomor & Label',
      stepCode: 'Kode Verifikasi',
      stepPassword: 'Kata Sandi 2FA',
      phoneHelper: 'Sertakan kode negara, mis. +62812xxxx.',
      sendCode: 'Kirim Kode',
      code: 'Kode dari Telegram',
      codeHelper: 'Masukkan kode yang dikirim ke aplikasi Telegram Anda.',
      password: 'Kata sandi verifikasi dua langkah',
      submit: 'Verifikasi',
      success: 'Akun berhasil terhubung.',
    },
  },

  products: {
    subtitle: 'Katalog produk, harga, opsi, dan pemetaan workflow (F6).',
    add: 'Tambah Produk',
    edit: 'Ubah Produk',
    name: 'Nama',
    price: 'Harga',
    sku: 'SKU',
    description: 'Deskripsi',
    imageUrl: 'URL Gambar',
    supplier: 'Supplier',
    workflow: 'Workflow',
    stockMode: 'Mode Stok',
    stockModeManual: 'Manual (atur sendiri)',
    stockModeUnlimited: 'Unlimited (tanpa batas)',
    stock: 'Jumlah Stok',
    active: 'Tampil di Storefront',
    options: 'Opsi',
    optionKey: 'Kunci',
    optionValue: 'Nilai',
    optionPrice: 'Harga',
    addOption: 'Tambah Opsi',
    savePrice: 'Simpan Harga',
    editPriceHint: 'Perubahan harga berlaku untuk pesanan berikutnya dan dicatat di audit.',
    deleteConfirm: 'Hapus produk ini dari katalog?',
    noSupplier: 'Tanpa supplier',
    noWorkflow: 'Tanpa workflow',
  },

  botConfig: {
    subtitle: 'Konfigurasi storefront bot: token, teks, menu, dan branding (F17).',
    tabs: { branding: 'Branding', text: 'Teks Bot', menu: 'Menu & Tombol', token: 'Token' },
    brandName: 'Nama Toko',
    logoUrl: 'URL Logo',
    supportContact: 'Kontak Support',
    botToken: 'Token Bot',
    botTokenHelper: 'Token bot Telegram (write-only). Isi hanya untuk mengganti.',
    localeTab: 'Bahasa',
    textKeys: {
      welcome: 'Pesan Selamat Datang',
      menu: 'Teks Menu',
      buttons: 'Label Tombol',
      payInstructions: 'Instruksi Pembayaran',
      success: 'Pesan Sukses',
      fail: 'Pesan Gagal',
      help: 'Bantuan',
    },
    menuBuilder: 'Penyusun Menu',
    menuLabel: 'Label Tombol',
    menuAction: 'Aksi',
    addButton: 'Tambah Tombol',
    moveUp: 'Naik',
    moveDown: 'Turun',
    remove: 'Hapus',
    preview: 'Pratinjau Pesan',
    previewHint: 'Pratinjau contoh pesan bot berdasarkan konfigurasi saat ini.',
  },

  broadcast: {
    subtitle: 'Kirim pesan ke seluruh pelanggan bot dan pantau progres pengirimannya.',
    composeTitle: 'Susun Broadcast',
    message: 'Pesan',
    messagePlaceholder: 'Tulis pesan yang akan dikirim ke semua pelanggan…',
    imageUrl: 'URL Gambar (opsional)',
    imageUrlPlaceholder: 'https://…',
    send: 'Kirim Broadcast',
    sendConfirm:
      'Pesan ini akan dikirim ke SEMUA pelanggan bot. Tindakan ini tidak dapat dibatalkan. Lanjutkan?',
    sent: 'Broadcast dimulai. Progres pengiriman akan tampil di riwayat.',
    emptyMessage: 'Pesan tidak boleh kosong.',
    invalidImageUrl: 'URL gambar harus berupa link http:// atau https://.',
    historyTitle: 'Riwayat Broadcast',
    columns: {
      message: 'Pesan',
      status: 'Status',
      targets: 'Target',
      sent: 'Terkirim',
      failed: 'Gagal',
      time: 'Waktu',
    },
  },

  orders: {
    subtitle: 'Pesanan pelanggan, status, dan tindakan manual.',
    id: 'ID Pesanan',
    customer: 'Pelanggan',
    product: 'Produk',
    amount: 'Jumlah',
    status: 'Status',
    created: 'Dibuat',
    detailTitle: 'Detail Pesanan',
    timeline: 'Linimasa',
    linkedExecution: 'Eksekusi Terkait',
    openExecution: 'Buka di Monitoring',
    payment: 'Pembayaran',
    retryConfirm: 'Jalankan ulang pemenuhan untuk pesanan ini?',
    refundConfirm: 'Proses refund untuk pesanan ini? Tindakan ini tidak dapat dibatalkan.',
    filterStatus: 'Status',
    filterFrom: 'Dari Tanggal',
    filterTo: 'Sampai Tanggal',
    noExecution: 'Belum ada eksekusi terkait.',
    noPayment: 'Belum ada pembayaran.',
  },

  customers: {
    title: 'Pelanggan',
    subtitle: 'Pelanggan storefront bot: aktivitas, saldo, dan status blokir.',
    columns: {
      username: 'Username / Nama',
      telegramId: 'Telegram ID',
      language: 'Bahasa',
      orderCount: 'Order',
      totalSpent: 'Total Belanja',
      balance: 'Saldo',
      lastOrderAt: 'Order Terakhir',
      createdAt: 'Gabung',
      status: 'Status',
    },
    stats: {
      total: 'Total Pelanggan',
      blocked: 'Diblokir',
      withOrders: 'Pernah Order',
      topLanguage: 'Bahasa Terbanyak',
    },
    status: {
      active: 'Aktif',
      blocked: 'Diblokir',
    },
    actions: {
      block: 'Blokir',
      unblock: 'Buka Blokir',
    },
    blockConfirm: {
      title: 'Blokir pelanggan',
      message:
        'Blokir pelanggan ini? Mereka tidak akan bisa memesan melalui bot sampai blokir dibuka.',
      confirmLabel: 'Ya, blokir',
    },
    unblockConfirm: {
      title: 'Buka blokir pelanggan',
      message: 'Buka blokir pelanggan ini agar bisa kembali memesan melalui bot?',
      confirmLabel: 'Ya, buka blokir',
    },
    toast: {
      blocked: 'Pelanggan diblokir',
      unblocked: 'Blokir pelanggan dibuka',
    },
    filters: {
      search: 'Cari username / Telegram ID',
      language: 'Bahasa',
      blocked: 'Status',
      blockedAll: 'Semua',
      blockedOnly: 'Diblokir',
      activeOnly: 'Aktif',
    },
    noName: 'Tanpa nama',
    noUsername: 'Tanpa username',
    never: 'Belum pernah',
  },

  payments: {
    subtitle: 'Transaksi Pakasir dan rekonsiliasi.',
    order: 'Pesanan',
    method: 'Metode',
    amount: 'Jumlah',
    fee: 'Biaya',
    status: 'Status',
    txnId: 'ID Transaksi',
    expiry: 'Kedaluwarsa',
    vaNumber: 'Nomor VA',
  },

  monitoring: {
    subtitle: 'Eksekusi langsung dengan grafik read-only dan kontrol.',
    activeList: 'Eksekusi Aktif',
    detail: 'Detail Eksekusi',
    selectHint: 'Pilih eksekusi untuk melihat grafik dan streaming langsung.',
    currentNode: 'Node saat ini',
    elapsed: 'Durasi',
    controls: 'Kontrol',
    stream: 'Aliran Kejadian',
    variables: 'Variabel',
    noneSelected: 'Tidak ada eksekusi dipilih',
    clear: 'Bersihkan',
    historyFallback: 'Riwayat langkah (eksekusi sudah selesai)',
    eventLog: {
      stepEntered: '→ masuk node',
      executionStarted: 'eksekusi dimulai',
      stepHistory: 'riwayat',
    },
  },

  logs: {
    subtitle: 'Aliran log langsung, dead-letter, dan audit.',
    tabs: { live: 'Log Langsung', deadLetter: 'Dead-letter', audit: 'Audit' },
    filterLevel: 'Level',
    filterSearch: 'Cari pesan',
    deadLetterEmpty: 'Tidak ada job gagal di dead-letter.',
    auditEmpty: 'Belum ada aktivitas admin tercatat.',
    liveHint: 'Log langsung mengalir dari eksekusi yang sedang berjalan.',
  },

  settings: {
    subtitle: 'Konfigurasi sistem: port, secret, 2FA, dan kunci pembayaran.',
    sections: {
      general: 'Umum',
      security: 'Keamanan',
      payment: 'Pembayaran',
    },
    bindAddress: 'Alamat Bind',
    port: 'Port',
    sessionSecret: 'Session Secret',
    totp: 'Autentikasi Dua Faktor (TOTP)',
    totpEnabled: '2FA aktif untuk akun ini.',
    totpDisabled: '2FA belum diaktifkan.',
    pakasirApiKey: 'Kunci API Pakasir',
    pakasirWebhookSecret: 'Webhook Secret Pakasir',
    readOnlyHint: 'Beberapa nilai dikelola melalui environment server dan hanya ditampilkan.',
  },

  docs: {
    title: 'Dokumentasi Workflow Builder',
    subtitle: 'Panduan lengkap: konsep, katalog node, regex, dan contoh workflow.',
    nodeCatalog: 'Katalog Node',
  },

  workflows: {
    subtitle: 'Bangun dan uji alur pemenuhan pesanan (n8n-style).',
    add: 'Workflow Baru',
    name: 'Nama',
    supplier: 'Supplier',
    version: 'Versi',
    status: 'Status',
    updated: 'Diperbarui',
    open: 'Buka Builder',
    builder: {
      untitled: 'Workflow tanpa nama',
      save: 'Simpan',
      validate: 'Validasi',
      test: 'Uji',
      account: 'Akun uji',
      palette: 'Node',
      config: 'Konfigurasi Node',
      noSelection: 'Pilih node untuk mengatur konfigurasinya.',
      versions: 'Versi',
      rollback: 'Kembalikan',
      rollbackConfirm: 'Kembalikan workflow ke versi ini? Perubahan yang belum disimpan akan hilang.',
      validationOk: 'Workflow valid.',
      validationErrors: 'Workflow memiliki masalah.',
      testStarted: 'Eksekusi uji dimulai.',
      selectAccountFirst: 'Pilih akun uji terlebih dahulu.',
      addNodeHint: 'Seret node dari panel kiri ke kanvas.',
      smallScreen: 'Editing workflow memerlukan layar lebih besar.',
      smallScreenHint: 'Gunakan perangkat desktop untuk mengedit grafik node.',
      executionDrawer: 'Aliran Eksekusi',
      deleteNode: 'Hapus Node',
      branchPorts: 'Port cabang',
      switchCases: 'Kondisi (cases)',
      addCase: 'Tambah Kondisi',
      removeCase: 'Hapus kondisi',
      caseValue: 'Nilai',
      emptyCanvas: 'Kanvas masih kosong',
      emptyCanvasHint: 'Seret node dari panel kiri ke kanvas untuk mulai membangun alur.',
      edgeDeleteHint: 'Klik dua kali garis koneksi untuk menghapusnya (atau pilih lalu tekan Delete).',
      fitView: 'Sesuaikan tampilan',
      nodeHasErrors: 'Node ini memiliki kesalahan',
      nodeHasWarnings: 'Node ini memiliki peringatan',
    },
    /**
     * Config-panel field labels (Bahasa Indonesia). Technical tokens (regex, {{var}})
     * and code identifiers stay as-is — these are only the human-readable labels.
     */
    fields: {
      label: 'Label',
      text: 'Teks',
      parseMode: 'Mode Parse',
      command: 'Perintah',
      args: 'Argumen',
      strategy: 'Strategi',
      value: 'Nilai',
      fromPeer: 'Dari Peer',
      mode: 'Mode',
      pattern: 'Pola (Regex)',
      caseSensitive: 'Peka Huruf Besar/Kecil',
      delayMs: 'Jeda (ms)',
      jitterMs: 'Jitter (ms)',
      expression: 'Ekspresi',
      on: 'Berdasarkan (ekspresi)',
      regex: 'Regex',
      assignTo: 'Simpan ke',
      extractMode: 'Mode Ekstraksi',
      extractModeFirst: 'Baris pertama saja',
      extractModeAll: 'Semua baris (mis. banyak akun)',
      joinWith: 'Pemisah antar baris',
      name: 'Nama Variabel',
      input: 'Input',
      output: 'Output',
      maxAttempts: 'Percobaan Maksimum',
      backoff: 'Strategi Backoff',
      timeoutMs: 'Timeout (ms)',
      count: 'Jumlah',
      whileExpression: 'Ekspresi While',
      maxIterations: 'Iterasi Maksimum',
      payload: 'Payload',
      reason: 'Alasan',
      refund: 'Refund',
      template: 'Template',
    },
    /**
     * Friendly Indonesian display title + one-line description per node type, shown
     * in the palette. The code identifier (NodeType enum value) stays English; only
     * the user-facing display copy is localized. Technical node names are kept.
     */
    nodeDisplay: {
      START: { title: 'Mulai', description: 'Titik awal eksekusi workflow.' },
      SEND_MESSAGE: { title: 'Kirim Pesan', description: 'Kirim pesan teks ke bot supplier.' },
      SEND_COMMAND: { title: 'Kirim Perintah', description: 'Kirim perintah (mis. /start) ke bot.' },
      CLICK_BUTTON: { title: 'Klik Tombol', description: 'Tekan tombol inline pada pesan bot.' },
      WAIT_MESSAGE: { title: 'Tunggu Pesan', description: 'Tunggu pesan masuk dari bot.' },
      WAIT_RESPONSE: { title: 'Tunggu Respons', description: 'Tunggu respons yang cocok dengan pola.' },
      WAIT_BUTTON: { title: 'Tunggu Tombol', description: 'Tunggu tombol inline muncul.' },
      DELAY: { title: 'Jeda', description: 'Tunda eksekusi selama durasi tertentu.' },
      MATCH_TEXT: { title: 'Cocokkan Teks', description: 'Percabangan berdasarkan kecocokan teks.' },
      CONDITION: { title: 'Kondisi', description: 'Percabangan benar/salah dari ekspresi.' },
      SWITCH: { title: 'Switch', description: 'Percabangan multi-cabang berdasarkan nilai.' },
      EXTRACT_DATA: { title: 'Ekstrak Data', description: 'Ambil data dari teks dengan regex.' },
      SET_VARIABLE: { title: 'Set Variabel', description: 'Simpan nilai ke variabel workflow.' },
      TRANSFORM: { title: 'Transformasi', description: 'Ubah nilai input menjadi output.' },
      RETRY: { title: 'Coba Ulang', description: 'Ulangi langkah saat gagal.' },
      TIMEOUT: { title: 'Timeout', description: 'Batasi waktu tunggu langkah.' },
      LOOP: { title: 'Perulangan', description: 'Ulangi cabang beberapa kali.' },
      SUCCESS: { title: 'Sukses', description: 'Akhiri workflow dengan status berhasil.' },
      FAIL: { title: 'Gagal', description: 'Akhiri workflow dengan status gagal.' },
      DELIVER_TO_CUSTOMER: { title: 'Kirim ke Pelanggan', description: 'Kirim hasil ke pelanggan.' },
      API_ORDER: { title: 'Order via API', description: 'Pesan produk ke supplier eksternal melalui REST API.' },
    },
    categories: {
      trigger: 'Trigger',
      action: 'Action',
      wait: 'Wait',
      logic: 'Logic',
      data: 'Data',
      control: 'Control',
      terminal: 'Terminal',
    },
  },
} as const;
